Logging:
  LogLevel:
    Default: "Information"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Information"

Servers:
- Name: Foo
  Address: Bar

- Name: Syndicate Mothership
  Address: Honk
